Upgrading prom-client
mercadoni/elementals pull request #23
Opened 2021-10-29 23:02 UTC by joagranadosme

# Summary #
This PR:
  - Moves the prom-client package from `devDependencies` to `dependencies`
  - Upgrades the `prom-client` version to remove deprecation warnings.
  - Upgrades some other libraries.
  - Removes the logger running the test suite.

2021-11-02 17:43 UTC, anmrdz requested changes

2021-11-02 17:43 UTC, anmrdz commented on package-lock.json
> +      },
The linting is failing due to this package-lock, it seems you generated it in a different format because there are too many changes for 1 library upgraded compare to [package-lock](https://github.com/mercadoni/elementals/blob/d816527de79b7e4a9bc34d2c6f5d90c71ca35104/package-lock.json#L2580) , Can you generate it again? What command did you use to upgrade the prom client?

2021-11-02 18:09 UTC, joagranadosme commented on package-lock.json
> +      },
It is due to the `npm` version

2021-11-02 18:10 UTC, anmrdz approved these changes

2021-11-02 18:44 UTC, cerodriguezl commented on package.json
> +    "prom-client": "14.0.0",
Thanks, @joagranadosme. I think we need to keep `prom-client` as a peer-dependency and dev-dependency, instead of a regular dependency. I'm pretty sure we had to make that change to solve issues in projects that already include `prom-client` (like Heimdall).  We were having problems when two copies of prom-client (system copy + elementals copy) are running at the same time.

2021-11-03 22:55 UTC, anmrdz approved these changes

2021-11-04 15:03 UTC, cerodriguezl approved these changes

2021-11-04 15:04 UTC, merged